require("config.misc")
require("config.monitors")
require("config.appearance")
require("config.layout")
require("config.input")
require("config.rules")
require("config.binds")
require("config.tvgamemode")